IMPORT RABDOM
IMPORT TIME

secret_number = random.randint(1.100)

attempts = 0
max_attempts = 2
score = 0 
leaderboard =[]

#create a time function

def timer(start_time)

#Display Menu

print(*User menu*)
print(*Settings*)
print("2.profile")


IF condition: 
 refiloe = 37
  IF refiloe < 17:
   print(*I AM YOOUNG*)
 ELSE:
  print(*i am aged*)



if guess == score_number:
 print (*congrats you've won*) 
 
# define functions to calculate score

def calculate_score(attempt)
 return 10*attemps

if attempts ==1
 return calculate-SCORE-5
 ELSE:
  RETURN calculate_score+10

a=1
 b=2
  def add_numbers(1+2)
results = a+b
return results











#problem statements
# 1.IMAGEN YOU ARE WORKING ON A PROJECT WITH A TEAM, AND YOU NEED TO BE ABLE TO KEEP
#TRACK OF ALL THE TASK MEMBERS DO.HOW WILL YOU SIMPLIFY THIS COLLABORATION

#2. AN EDUCATOR WANTS TO ENGAGE LEANERS OF AN ECD CENTER FOR SPECIAL NEEDS LEANERS 
#AND TEACH THEM IN A WAY THAT IS ENTERTAINING AND FUN,
#WHAT PROGRAMME CAN SHE USE FOR THIS?

#3. PICTURE YOURSELF AS A LIBRARIAN MANAGING A BUSY LIBRARY.WHAT PROGRAM CAN YOU USE
#TO CATALOG BOOKS, TRACK BORROWING AND PROVIDE AN EASY WAY FOR ALL LIBRARY MEMBERS
#TO ACCESS RESOURCE?
























































